### ISSUE TITLE
pls add ElementsMatch assert

### ISSUE THREAD

**Issue by maaaaaash** [ozontech/allure-go#20]
please add ElementsMatch as a assert

**Comment by koodeex** [comment]
due this issue next asserts will be add from testify:

- `Exactly`
- `Same`
- `NotSame`
- `EqualValues`
- `NotEqualValues`
- `EqualError`
- `ErrorIs`
- `ErrorAs`
- `ElementsMatch`
- `DirExists`
- `Condition`
- `Zero`
- `NotZero`
