### ISSUE TITLE
Test falls in afterEach step

### ISSUE THREAD

**Issue by ismonsen** [ozontech/allure-go#39]
**Describe the bug**
I am running a test in Suite in gitlab. I had an error in test's step with message "index out of range [0]. Allure was logging an error in the afterEach step instead of an error inside test. Moreover, the element I accessed has len = 1, so this shouldn't be an error.

**To Reproduce**
1. Used func: suite.RunSuite
2. What you actually wanted to do: to get test passed :)
3. What has been expected:  noError
4. What you got actual: error in afterEach step
5. Error Log (if any):
`
afterEach panicked: runtime error: index out of range [0] with length 0
goroutine 509 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
github.com/ozontech/allure-go/pkg/framework/runner.(*runner).RunTests.func1.3.1.2()
	/builds/Nx2CE54f/0/bx/pdp-api/.cache/go/pkg/mod/github.com/ozontech/allure-go/pkg/framework@v0.6.18/runner/runner.go:182 +0x85
panic({0x14edf00, 0xc000dbee28})
	/usr/local/go/src/runtime/panic.go:884 +0x212
gitlab.*.ru/bx/pdp-api/e2e/internal/steps.(*Helper).GetDigitalBookLitres.func1()
	/builds/Nx2CE54f/0/bx/pdp-api/e2e/internal/steps/item.go:111 +0x2a5
gitlab.*.ru/marketplace/qa/tools/qa_pack/pkg/utilities.Poll(0x18956c0?, 0xc0004ab6b0?, 0xc000d39198)
	/builds/Nx2CE54f/0/bx/pdp-api/.cache/go/pkg/mod/gitlab.*.ru/marketplace/qa/tools/qa_pack@v0.3.15/pkg/utilities/utilities.go:123 +0xfb
gitlab.*.ru/bx/pdp-api/e2e/internal/steps.(*Helper).GetDigitalBookLitres(0xc00040abd0, {0x18956c0, 0xc0004ab6b0}, {0x18acc20, 0xc0000ef7a0})
	/builds/Nx2CE54f/0/bx/pdp-api/e2e/internal/steps/item.go:107 +0x176
gitlab.*.ru/bx/pdp-api/e2e/suites.(*WebSmokeSuite).TestWebAddToCartV8wDigitalBook(0xc000072780, {0x18acc20, 0xc0000ef7a0})
	/builds/Nx2CE54f/0/bx/pdp-api/e2e/suites/web_suite.go:176 +0x130
reflect.Value.call({0xc000216a20?, 0xc000131830?, 0x30?}, {0x16067f1, 0x4}, {0xc0005a3920, 0x2, 0x18?})
	/usr/local/go/src/reflect/value.go:584 +0x8c5
reflect.Value.Call({0xc000216a20?, 0xc000131830?, 0x10?}, {0xc0005a3920?, 0x10?, 0x2561240?})
	/usr/local/go/src/reflect/value.go:368 +0xbc
github.com/ozontech/allure-go/pkg/framework/runner.(*testMethod).GetBody.func1({0x18acc20?, 0xc0000ef7a0?})
	/builds/Nx2CE54f/0/bx/pdp-api/.cache/go/pkg/mod/github.com/ozontech/allure-go/pkg/framework@v0.6.18/runner/tests.go:150 +0x2b1
github.com/ozontech/allure-go/pkg/framework/runner.(*runner).RunTests.func1.3.1(0xc000ba9ba0)
	/builds/Nx2CE54f/0/bx/pdp-api/.cache/go/pkg/mod/github.com/ozontech/allure-go/pkg/framework@v0.6.18/runner/runner.go:205 +0x2e7
testing.tRunner(0xc000ba9ba0, 0xc000b8e190)
	/usr/local/go/src/testing/testing.go:1446 +0x10b
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1493 +0x35f
`

**Expected behavior**
If test falls, allure logs error inside test

**Comment by koodeex** [comment]
Not actual
