### ISSUE TITLE
Error is not included in the allure report if it is in the BeforeAll hook.

### ISSUE THREAD

**Issue by AleksandrGurkin** [ozontech/allure-go#6]
**Describe the bug**
If during the initialization of the suite you add a step with a check that will fall, the entire suite in the allure report is simply ignored. The information in the console is displayed correctly

**To Reproduce**

```
import (
	"testing"

	"github.com/ozontech/allure-go/pkg/framework/provider"
	"github.com/ozontech/allure-go/pkg/framework/suite"
)

type BeforeAfterDemoSuite struct {
	suite.Suite
}

func (s *BeforeAfterDemoSuite) BeforeAll(t provider.T) {
	t.WithNewStep("Before suite Step", func(sCtx provider.StepCtx) {
		sCtx.Require().Equal(1, 2, "lol")
	})
}

func (s *BeforeAfterDemoSuite) TestBeforeAfterTest(t provider.T) {
	t.Epic("Demo")
	t.Feature("BeforeAfter")
	t.Title("Test wrapped with SetUp & TearDown")
	t.Description(`
		This test wrapped with SetUp and TearDown containert.`)

	t.Tags("BeforeAfter")
}

func TestBeforesAfters(t *testing.T) {
	t.Parallel()
	suite.RunSuite(t, new(BeforeAfterDemoSuite))
}
```

**Expected behavior**
Display the suite in the report, with an error in the setup and a skipped body of tests.

**Comment by koodeex** [comment]
@AleksandrGurkin , FYI

issue can be tested at v0.6.6 tag (beta)

It will be a great pleasure to get your feed back

Also, I will be really happy if you could [review PR](https://github.com/ozontech/allure-go/pull/10)

**Comment by koodeex** [comment]
@AleksandrGurkin , FYI

New beta tag v0.6.7 released
