### ISSUE TITLE
Documentation mistakes in examples for the suite configuration

### ISSUE THREAD

**Issue by homiache** [ozontech/allure-go#7]
There are few documentation mistakes in this example for the [suite configuration](https://github.com/ozontech/allure-go#configure-suite):

```go
package suite_demo

import (
	"testing"

	"github.com/ozontech/allure-go/pkg/framework/provider"
	"github.com/ozontech/allure-go/pkg/framework/runner"
    "github.com/ozontech/allure-go/pkg/framework/suite"
)

type DemoSuite struct {
	suite.Suite
}

func (s *DemoSuite) TestSkip(t provider.T) {
	t.Epic("Demo")
	t.Feature("Suites")
	t.Title("My first test")
	t.Description(`
		This test will be attached to the suite DemoSuite`)
}

func TestSkipDemo(t *testing.T) {
	t.Parallel()
	runner.RunSuite(t, new(SkipDemoSuite))
}
```

Seems the `TestSkipDemo` function should be like that:

```go
func TestSkipDemo(t *testing.T) {
	t.Parallel()
	suite.RunSuite(t, new(DemoSuite))
}
```

- `new(DemoSuite)` instead of the `new(SkipDemoSuite)` cause the `SkipDemoSuite` struc doesn't exist in the example.
- `suite.RunSuite` instead of the `runner.RunSuite` cause no any `RunSuite` method for the `runner`

## Additional info
Just a picture with the current code example:

![image](https://user-images.githubusercontent.com/100802205/170704041-a21ae15d-ff2e-4f45-bbfb-79a6a30c2fbc.png)

**Comment by koodeex** [comment]
@homiache merged :) Thanks a lot for the help!
