### ISSUE TITLE
Run test failed with error: Failed marshal Result

### ISSUE THREAD

**Issue by jurvanova** [ozontech/allure-go#71]
**Describe the bug**
Run test fails with error message like:  
Failed marshal Result: json: error calling MarshalJSON for type json.RawMessage: invalid character 'c' after top-level value
Failed marshal Result: json: error calling MarshalJSON for type json.RawMessage: invalid character 'i' after top-level value

**To Reproduce**
Error appears in github.com/ozontech/allure-go/pkg/allure@v0.6.10/container.go 
func printContainer()

go.mod
github.com/ozontech/allure-go/pkg/framework v0.6.26
github.com/ozontech/allure-go/pkg/allure v0.6.10

go.sum
github.com/ozontech/allure-go/pkg/allure v0.6.10 h1:chHzORobuPf3UJz23c2n3PIy6QaoxnLgaei2pwBiVxY=
github.com/ozontech/allure-go/pkg/allure v0.6.10/go.mod h1:4oEG2yq+DGOzJS/ZjPc87C/mx3tAnlYpYonk77Ru/vQ=
github.com/ozontech/allure-go/pkg/framework v0.6.26 h1:sHOBTQG5LFQhLFeaAi1zAI9fCSc/L0AbCweO+fgaNOQ=
github.com/ozontech/allure-go/pkg/framework v0.6.26/go.mod h1:iMUFp2UHRFtEGiVajXGVGavlSurfrSfYe9fmutgbvmI=

**Expected behavior**
Test runs without fails

![Снимок экрана 2023-07-17 в 20 36 14](https://github.com/ozontech/allure-go/assets/55279046/50ac1235-a2e0-4de5-a868-0e02113a1f4a)

**Comment by ismonsen** [comment]
Hello! After update `go get github.com/ozontech/allure-go/pkg/framework@v0.6.26` I have same problem 
`Failed marshal Result: json: error calling MarshalJSON for type json.RawMessage: invalid character 'p' after top-level value`

**Comment by jurvanova** [comment]
issue solved, thanks
