### ISSUE TITLE
Wrong using defer in example

### ISSUE THREAD

**Issue by KolesnikDmitriy** [ozontech/allure-go#77]
**Describe the bug**
Incorrect example with defer. Require my stops test execution when a test result fails, and defer stack will not fill.

**To Reproduce**
look through example:
https://github.com/ozontech/allure-go/blob/master/examples/suite_demo/setup_test.go#L92

**Expected behavior**
defer should executed right after context declaration

**Comment by siller174** [comment]
what a main idea of this MR?

**Comment by KolesnikDmitriy** [comment]
The main idea is fix documentation to avoid confusion of newcomers. They may start using defer after t.Require

**Comment by koodeex** [comment]
In common case it make sense but in that example the reason why defer stay there is to highlight semantic of  WithTearDown function

It looks like common sense to me that you need to put in the begging of Test

Gimme think day or two about that

**Comment by KolesnikDmitriy** [comment]
fixed in https://github.com/ozontech/allure-go/pull/78
